backend:
  name: github
  repo: tsettle44/gatsbySite

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: readTime, label: Read Time }
      - { name: author, label: Author, default: Tom Settle }
      - {
          name: authorImage,
          label: Author Image,
          widget: image,
          default: “/assets/img_3915.jpg”,
        }
      - { name: coverImage, label: Cover Image, widget: image }
      - { name: preview, label: Preview }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Projects
    folder: projects
    create: true
    identifier_field: name
    fields:
      - { name: name, label: name }
      - { name: description, label: Description }
      - { name: link, label: Link }
      - { name: sourceCode, label: Source Code }
      - { name: displayImage, label: Display Image, widget: image }
  - name: albums
    label: Albums
    folder: albums
    create: true
    identifier_field: name
    fields:
      - { name: name, label: name }
      - { name: description, label: Description }
      - { name: path, label: path }
      - { name: displayImage, label: Display Image, widget: image }
      - { name: body, label: Body, widget: markdown }
